# Generated by Django 2.2.12 on 2021-05-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_rol', models.PositiveSmallIntegerField(choices=[(1, 'Academico'), (2, 'Usuario S'), (3, 'Grupo vulnerable')], default=1)),
                ('user_gender', models.PositiveSmallIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Otro')], default=2)),
            ],
        ),
    ]
